### ISSUE TITLE
Map goes all the way to 2019, but there's no data in 2019

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#18]
Map should go only up to the last year of data...

**Comment by infowetrust** [comment]
Including 2019 was a hack to make the custom scrollbar work.

Alternatives either required too much coding or were much less attractive (think of our original scrollbar).

If it is important to fix this then I recommend we return to the normal scroll bar.

**Comment by jorgeguzmanecon** [comment]
OK.. .Let's leave as we have, I am tagging this issue as a "wontfix"
