### ISSUE TITLE
Add a mention for credits in the map and copyright

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#19]
Please add a mention to Columbia University in the map.  Ideally one would be able to fit both the Columbia Data Science Institute logo and the Columbia Business School logo, but if not the university logo itself would be OK. 

Also, add a (C) symbol with RJ Andrews, Catherine Fazio, Jorge Guzman, and Scott Stern.

**Comment by infowetrust** [comment]
Merging this issue with https://github.com/infowetrust/startup-nation/issues/19
