### ISSUE TITLE
Improve the amount of detail shown in the map for the geography 

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#21]
Maybe this is the best one, but is there a possibility that a different layer for OpenStreetMap can look better in our map? Specifically, I sometimes feel there's a little bit of detail missing that would be useful to understand were different things are (e.g. road names, airports, or topography).

I'm attaching a standard OSM view of Lexington KY vs our map so you can see.  It's much easier to make sense of where things are in the OSM.

**OSM Standard Map**
![Screen Shot 2019-05-02 at 9 43 23 AM](https://user-images.githubusercontent.com/13614516/57079769-0df19400-6cbf-11e9-8a9e-61fbf494d789.png)

**SCP Map**
![Screen Shot 2019-05-02 at 9 43 29 AM](https://user-images.githubusercontent.com/13614516/57079792-1649cf00-6cbf-11e9-89fe-b13fc0e255c7.png)

**Comment by infowetrust** [comment]
add road (highway) names, mountains, urban shading

**Comment by infowetrust** [comment]
Approach taken was to make this look good in state of interest (not shaded out states):

`road-motorway` layer emphasized (new on right) with darker color:

![image](https://user-images.githubusercontent.com/20571941/57155576-aefc4f80-6d90-11e9-8c7c-70d6970154c5.png)

`hillshade` layer added. This is not perfect but a good start:

![image](https://user-images.githubusercontent.com/20571941/57157745-6e073980-6d96-11e9-9ed2-9559fefb9501.png)

**Comment by infowetrust** [comment]
Ugh, I hate how the highway shields look with data. I'm going to hide them for now. We can revisit later:

![image](https://user-images.githubusercontent.com/20571941/57165366-ba10a900-6dab-11e9-87bd-36a72aa3c9ef.png)

**Comment by infowetrust** [comment]
Updated mountain textures & forest shading.
