### ISSUE TITLE
Add a link to data download

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#23]
Could we add another link, next to "See methodology | Take a screenshot" that says "Download  data" and sends you the the data SCP page?

**Comment by infowetrust** [comment]
@jorgeguzmanecon  What is the page address that this link should go to?

**Comment by jorgeguzmanecon** [comment]
http://www.startupcartography.com/data

Yupeng and I will make this that end of the website works.  Would you please assign to Yupeng once it's setup so we can do our side?

**Comment by infowetrust** [comment]
Link added to KY & USA maps.
