### ISSUE TITLE
SCP sidebar looks odd in firefox

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#24]
sidebar looks good in Safari and Chrome, but in firefox the year scrollbar is smushed and the circle sizes for few vs many are cutoff.. See picture attached.

![Screen Shot 2019-05-02 at 10 01 29 AM](https://user-images.githubusercontent.com/13614516/57080793-4b572100-6cc1-11e9-9137-aa688e58101b.png)

**Comment by infowetrust** [comment]
Looking at it with Firefox on laptop screen at 100% zoom (which I think should be our default) it looks OK to me (see below image). On bigger screens and with different zoom levels things may get smushed a little, but it is still operable. I recommend we close this @jorgeguzmanecon 

![image](https://user-images.githubusercontent.com/20571941/57097286-3c29a080-6ccc-11e9-816c-caae6634f235.png)

**Comment by jorgeguzmanecon** [comment]
Closing as wontfix.
