### ISSUE TITLE
Change page title to Startup Cartography Project at Columbia University

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#25]
This is on the HTML and assigned to yupeng.

**Comment by infowetrust** [comment]
Do you mean the text in the page tab (below: _SCP: Kentucky_)?

If so, then this should be updated in index.html line 6:
`<title>SCP: Kentucky</title>`

The problem with your suggested title is that it is too long: it will never fully display in a tab.

![image](https://user-images.githubusercontent.com/20571941/57097770-70519100-6ccd-11e9-950f-35a5b0d5b80b.png)

**Comment by jorgeguzmanecon** [comment]
Right.. this is assigned to Yupeng

**Comment by infowetrust** [comment]
updated to:
![image](https://user-images.githubusercontent.com/20571941/57152338-13ff7780-6d88-11e9-8942-79bcc32e2ee3.png)
