### ISSUE TITLE
Change "take a screenshot" text

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#26]
The current text, "take a screenshot", seems to make the user believe that a screenshot will be taken.  Could we change to say more clearly that it will only be some instruction.  Maybe?

"Need a screenshot? See how"

With the see how redirecting to the current link?

I think this would work.

**Comment by infowetrust** [comment]
Updated to _Learn how to Screenshot_ for Kentucky and USA maps.
