### ISSUE TITLE
Can we add a citation link?

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#27]
The people the use this website should have a way to credit us for them.  Is there a way to add a link that says "how to cite?" and then displays our citatioon, which I think is.

Andrews, RJ, C Fazio, J Guzman, and S Stern. 2019. _The Startup Cartography Project_ Url: http://www.startupcartography.com

**Comment by infowetrust** [comment]
**Also** Please add a mention to Columbia University in the map. Ideally one would be able to fit both the Columbia Data Science Institute logo and the Columbia Business School logo, but if not the university logo itself would be OK.

Also, add a (C) symbol with RJ Andrews, Catherine Fazio, Jorge Guzman, and Scott Stern.

**Comment by infowetrust** [comment]
@jorgeguzmanecon we need some clarity about: citation, copyright, and Columbia reference.

What should this text be? Where should it all go on the map?
