### ISSUE TITLE
Scale map to use all data 

### ISSUE THREAD

**Issue by jorgeguzmanecon** [infowetrust/startup-nation#30]
Increase the map to be national and provide yupeng the updated instructions (if any updates are necessary) to use this map.

**Comment by infowetrust** [comment]
zoom and bounds restored:

`// Set bounds to USA (with a big buffer)
var bounds = [
  [-175, 0], // Southwest coordinates X,Y
  [-35, 70] // Northeast coordinates X,Y
];
var centerPoint = [-105, 38]

//Load a new map in the 'map' HTML div
var map = new mapboxgl.Map({
  container: 'map',
  
  //startupcarto
  //state fills created using tutorial https://docs.mapbox.com/help/tutorials/style-single-country/
  //with data from http://www.naturalearthdata.com/downloads/10m-cultural-vectors/

  style: 'mapbox://styles/startupcarto/cjrdwob723lhr2tmqwm09a3mk',
  attributionControl: false,
  hash: true, //populates URL with zoom level and coordinates of current view
  center: centerPoint,
  zoom: 3.5,
  minZoom: 3,
  maxZoom: 15,
  maxBounds: bounds // Sets var bounds as max

});`
